### ISSUE TITLE
Defining aliases

### ISSUE THREAD

**Issue by laughedelic** [JunoLab/atom-latex-completions#1]
Would be nice to be able to define aliases for some symbols or override prefixes. For example, I use these shortcuts:

``` json
{
  "ox": "⊗",
  "o+": "⊕",
  "to": "→",
  "e": "ɛ",
  ...
}
```

Probably a setting with a path to some additional `json` with these definitions would help..

**Comment by MikeInnes** [comment]
How does 69842725462d29d724270659f4672f397596ecfd look to you? If it's what you were going for I'll push a release.

**Comment by MikeInnes** [comment]
Hmm looks like the selector config isn't working though

**Comment by MikeInnes** [comment]
Fixed

**Comment by laughedelic** [comment]
@one-more-minute :+1: thanks! yes that's what I was thinking about. I would ask for one more option: to be able to turn on/off the default list of completions. For example, I want to copy some part of it (only the symbols I need) to the custom json and turn off the rest.

**Comment by laughedelic** [comment]
Also, not so essential, but still useful: being able to set several custom files (same setting, just list then comma separated). Then you can store different sets of symbols (math, greek, strange arrows, etc.) in different files (easier to maintain).

**Comment by MikeInnes** [comment]
Done & done.

**Comment by laughedelic** [comment]
wonderful! thanks a lot! :+1:

**Comment by MikeInnes** [comment]
No problem!

**Comment by capn-freako** [comment]
Could you provide an example of the necessary syntax for a custom completions file, please?

Also, should I use DOS file naming when running under Windows?

Thanks!
