### ISSUE TITLE
Sup- and super-scripts?

### ISSUE THREAD

**Issue by tseaward** [JunoLab/atom-latex-completions#10]
Is it possible to support subscripts and superscripts, i.e. `x_1` is x<sub>1</sub> and `x^2` is x<sup>2</sup>?

**Comment by sglyon** [comment]
This is already supported, though the syntax is a little goofy.

You need to do `x\_1TAB` and `x\^2TAB`

**Comment by alexpattyn** [comment]
I am having issues with `\_y`. It appears that `\_y` goes to ¥ and not the subscript y. Is there a mapping for the subscript of y that I can't find? This would be useful for documentation that indexes spatial coordinates.
