### ISSUE TITLE
Theta is different between Atom and Julia REPL

### ISSUE THREAD

**Issue by andyferris** [JunoLab/atom-latex-completions#11]
Hi,

I'm getting two different symbols from Atom and from the Julia REPL for \theta. These are:

θ
Θ

They look different here on the website but the same in Atom, which is super confusing!

**Comment by MikeInnes** [comment]
Interesting, they do seem to be different. We generate symbols using Julia's map, but it's possible Julia has changed and we just need to update.

**Comment by MikeInnes** [comment]
Ok, that's not right, but I think what's happening is that Atom puts `Theta` above `theta` in the completions list – so you're completing with capital-theta which looks similar in monospace.

**Comment by andyferris** [comment]
Oops, silly me!

In general, I find Atom's completions to be quite spammy. It seems to want to "help" even after typing a correct identifier, so I'm constantly reaching for Esc or similar. This is yet another case of that...

**Comment by MikeInnes** [comment]
In theory we can change how Atom weights different completions, so that e.g. the case of the latex character is taken into account. Might be worth looking into eventually.

**Comment by pfitzseb** [comment]
Ref: https://github.com/atom/autocomplete-plus/issues/651
