### ISSUE TITLE
Turn off latex completions for .tex documents

### ISSUE THREAD

**Issue by cortner** [JunoLab/atom-latex-completions#13]
When I write a latex document, the latex completions package messes with my typing, occasionally replacing a tex macro with a unicode symbol. Could there be a hot-key to turn it off?

I tried to  add this to `keymap.cson`, but it didn't work. (?)

```
'atom-workspace':
  'alt-cmd-l': 'latex-completions:toggle-enabled'
```

**Comment by MikeInnes** [comment]
I went ahead and added an option to disable this in certain scopes, so from now on it won't appear in `.tex` or `.latex` by default. Let me know if that should be something different.

**Comment by cortner** [comment]
I think this is right. Maybe there could be an option  / hot-key to turn it on-off in other files as well? Thanks.

**Comment by MikeInnes** [comment]
Seems like a good idea but it's not something I'm that interested in doing myself. Feel free to send a patch though, it'd be pretty easy to implement.

**Comment by cortner** [comment]
When I find the time to learn js and how to code atom . . .
