### ISSUE TITLE
Backslash on Swedish keyboard

### ISSUE THREAD

**Issue by IngemarS** [JunoLab/atom-latex-completions#14]
To escape characters in Julia one should be able to use "\" the backslash, on a Swedish keyboard that normally happening with the AltGr+ the plus key ((one step to the right of the 0/zero key on the keyboard. This works f ex in the Julia REPL, but not in Atom/Juno and probably(?) has something to do with the latex-completions? I haven't yet found out how to circumvent this or if removing latex-completions is the only way, and what eventual side effects that would have?!

**Comment by pfitzseb** [comment]
This is an Atom issue -- use the [keyboard-localization](https://atom.io/packages/keyboard-localization) package to work around it until it's fixed.

**Comment by pfitzseb** [comment]
Should be fixed with latest Atom -- please reopen if you're still getting that bug.
