### ISSUE TITLE
Ordering of suggestions in drop-down list (case)

### ISSUE THREAD

**Issue by jmboehm** [JunoLab/atom-latex-completions#15]
Hi,

I'm getting suggestions in the drop-down list that do not reflect the case of what I typed, leading to somewhat unreasonable behaviour like this:

![screen shot 2016-07-21 at 14 56 30](https://cloud.githubusercontent.com/assets/17812941/17405130/9bcc9c46-5a5e-11e6-93f2-c06f80ec1df4.png)

A similar issue has been reported in autocomplete-plus (atom/autocomplete-plus#651) which may be the underlying problem -- but I don't understand the relationship between these packages well enough to judge.

**Comment by andyferris** [comment]
:+1: `\theta` has bit me too many times

**Comment by joshday** [comment]
I'm still seeing this issue with `\theta`.  Anyone else?  
<img width="238" alt="screen shot 2017-02-07 at 8 52 05 am" src="https://cloud.githubusercontent.com/assets/8075494/22693782/bb93209e-ed12-11e6-8466-568cfac85d42.png">
