### ISSUE TITLE
Completion of \theta does not match completion of the julia REPL

### ISSUE THREAD

**Issue by LMescheder** [JunoLab/atom-latex-completions#16]
When, I type `\theta` and hit tab in the julia REPL, I get 'θ' (U+03b8), whereas in atom-latex-completions I get 'Θ' (U+0398). This is annoying when I want to call a function written in juno from the julia REPL.

**Comment by pfitzseb** [comment]
Dup of #15.
Should probably be adressed over at autocomplete-plus, or we need to implement our own matching logic.
