### ISSUE TITLE
Too general scope

### ISSUE THREAD

**Issue by iagobaapellaniz** [JunoLab/atom-latex-completions#17]
Hello there.

I'm editing in LaTeX and it is a little annoying to hit [Escape] each time i try to write a formula on LaTeX.

On the other way it is very handy to have your package for Julia.

The scope of LaTeX is
`text.tex.latex`

Could you skip on suggesting auto-completions on it by default?

**Comment by pfitzseb** [comment]
Should be fixed in the newest version.
