### ISSUE TITLE
Substitution fails for fully typed unique leaves.

### ISSUE THREAD

**Issue by twadleigh** [JunoLab/atom-latex-completions#2]
For example, typing `\alpha<TAB>` works because `\Alpha` is an alternate substitution. Similarly, typing `\rightarrow<TAB>` works because it is a substring of a variety of substitutions. However, typing, _e.g._, `\rightarrowtail<TAB>` fails.

**Comment by MikeInnes** [comment]
This works fine for me on a blank buffer. Do you have a different way of reproducing it, or perhaps some info about your setup/config?

**Comment by twadleigh** [comment]
I see the same behavior on Linux and Windows. To ensure there were no weird interactions, I also disabled all (other) non-bundled packages. I can reproduce this in a blank buffer.

To clarify, completion works as long as I _don't_ fully type the otherwise-unique completion. _E.g._, typing `\rightarrowtai<TAB>` works. It is only when it is fully typed that it fails.

**Comment by swt30** [comment]
I find exactly the same behaviour as this, also with all non-default extensions disabled, on atom 1.0.15, Ubuntu 15.04.

**Comment by pfitzseb** [comment]
I can't reproduce this either -- in case this *doesn't* work for you on latest Atom and latex-completions, feel free to reopen this issue.

**Comment by twadleigh** [comment]
Just checked that it is working for me on Windows.
