### ISSUE TITLE
First option for completion of "\theta" is upper-case Θ, not lower-case θ

### ISSUE THREAD

**Issue by dmbates** [JunoLab/atom-latex-completions#21]
I'm not sure if this is fixable but it would save me a lot of trouble if it was.  I use the lower-case θ often in my code and end up staring at UndefVarError messages in Julia until I suddenly twig on to the fact that I used the upper-case character instead of the lower-case version.  In many fonts these two are difficult to distinguish.

**Comment by sglyon** [comment]
This always gets me with `\pi` and `\Pi`. 

Last time I checked this was an issue with Atom's autocomplete engine being case insensitive. Maybe @MikeInnes or @pfitzseb has more recent info?

**Comment by pfitzseb** [comment]
Dup of #15.
