### ISSUE TITLE
It doesn't work...

### ISSUE THREAD

**Issue by wtrtony** [JunoLab/atom-latex-completions#23]
I installed it，but I don't know why it doesn't work. Shall I install some packages else？

**Comment by pfitzseb** [comment]
No, this should work on its own. Try restarting Atom maybe?

**Comment by wtrtony** [comment]
I found out the reason... It's kind of silly...  In the settings, selector, (enable completions under these scopes),it needs a comma in the end.....
![image](https://cloud.githubusercontent.com/assets/17312605/21189768/b73a41f4-c25a-11e6-9455-75f2721523b2.png)

**Comment by pfitzseb** [comment]
Did you remove `.latex` from `Disable For Selector`? The trailing comma shouldn't be necessary in general.
