### ISSUE TITLE
Typing \subseteq gives a different symbol first

### ISSUE THREAD

**Issue by dpsanders** [JunoLab/atom-latex-completions#25]
Typing `\sub` gives `\subset` on top of the completion list.
Typing another `s` puts `\sqsubseteq` on top, and it does not go away even if I type the whole of `\subseteq`, so that pressing Enter then gives the wrong character.

**Comment by pfitzseb** [comment]
This is fixed on master via https://github.com/JunoLab/atom-latex-completions/pull/22.
