### ISSUE TITLE
Package simply not working at all

### ISSUE THREAD

**Issue by nathancarter** [JunoLab/atom-latex-completions#26]
I recently installed uber-juno, which brought this package in, because I'm learning Julia.  This package seems to have absolutely no effect.  I cannot get Atom to suggest a completion for `\alpha`, `\beta`, `\in`, etc.  The package is definitely enabled, no settings changed from when it was installed.  Any suggestions, or more data I can share to help you diagnose the problem?

**Comment by felixholub** [comment]
Same here, from the regularly downloaded package.

**Comment by pfitzseb** [comment]
Can you try opening the Dev Console (Ctrl-Shift-i) and report any erros you see there?

**Comment by felixholub** [comment]
All thata I see is probably unrelated to the completions package:
`spell-check:en-us Can't load en_US: Cannot find dictionary for en_US`

**Comment by felixholub** [comment]
My bad. I was trying arounf in a tex-file .... I'm sure @nathancarter has been smarter though.

**Comment by pfitzseb** [comment]
Yeah, I was just about to suggest you try it in a plain text file :)

**Comment by nathancarter** [comment]
Whoops, I just realized I let this issue go without my comments for so long that it got closed without actually being fixed.  My bad.
 * In response to the Dev Console, which I believe is Cmd+Opt+I on Mac, I see no messages.
 * In response to the question about the type of file, I've tried it in `.txt` and `.jl`, and neither works.
