### ISSUE TITLE
Disable does not work

### ISSUE THREAD

**Issue by ostrokach** [JunoLab/atom-latex-completions#29]
I am trying to disable `latex-completions` for Python files.

I entered the following into the "Disable For Selector" section:

    .tex, .latex, .py

But I still get latex completions when I enter `\` inside a Python file.

----

- Atom version 1.19.1
- `latex-completions` version: 0.3.3

**Comment by pfitzseb** [comment]
The 'scopes' that options refers to are actual scopes (e.g. what you get from `Editor: Log Cursor Scope`), not file extensions. Try
```
.tex, .latex, .python
```
instead (and don't forget to restart Atom to get the new behaviour).

**Comment by ostrokach** [comment]
Awesome, thanks!
