### ISSUE TITLE
Wrong completion of \varepsilon

### ISSUE THREAD

**Issue by hmarthinsen** [JunoLab/atom-latex-completions#3]
`\varepsilon` is currently mapped to ɛ (U+025B latin small letter open e). This is not recognized by XeLaTeX and is converted to a blank. The correct mapping is ε (U+03B5 greek small letter epsilon).

**Comment by MikeInnes** [comment]
Thanks for the report – could you please forward this to the [JuliaLang repo](https://github.com/JuliaLang/julia/issues), since that's where we get our completion mapping from?

**Comment by hmarthinsen** [comment]
OK, I've submitted it to JuliaLang.
