### ISSUE TITLE
autocompletion stopped working after some time

### ISSUE THREAD

**Issue by jjaiprakash** [JunoLab/atom-latex-completions#30]
It was working fine and suddenly stopped. Closing and Opening Atom does not recover.

**Comment by pfitzseb** [comment]
Do the completions not work anywhere or only not work in the ink console (if you're using that)?

**Comment by jjaiprakash** [comment]
I am trying to using inside Markdown documents. I tried using the default setting of 
.source, .text.
and also added .md,.gfm,.text.md  etc. 

It worked out of the box and then suddenly stopped working. 
Can it be impacted by settings from other packages like autocomplete-plus from atom?

Could it be related to a custom snippets.cson file that I added ?

**Comment by aterenin** [comment]
I have the same problem. Completions do not work anywhere. I see nothing related to them in the dev console.

**Comment by pfitzseb** [comment]
Did you try in a Plain Text file? What version of Atom/latex-completions are you using?

**Comment by aterenin** [comment]
Problem is fixed - was due to a package conflict.

**Comment by ssfrr** [comment]
can you clarify the package conflict? I'm having similar behavior. Recently it seems that my latex completions don't work anymore - I see the autocomplete list pop up, but pressing "tab" doesn't replace the text with the character.

It works fine in the Juno REPL (though that might just be using REPL code?)

In the dev console I see the following error when the completion box pops up:

```
completions.coffee? [sm]:40 Uncaught (in promise) TypeError: Cannot read property 'map' of null
    at Object.processCompletions (completions.coffee? [sm]:33)
    at completions.coffee? [sm]:36
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
```

**Comment by pfitzseb** [comment]
That looks like a julia-client error... you sure your Julia packages are up-to-date (specifically Atom.jl)?

**Comment by ssfrr** [comment]
ah, yes! That's it. I thought running `] up` from my project would update everything but I needed to go back to my `v1.0` environment and run `update` as well.

Thanks.
