### ISSUE TITLE
Latex completion takes 5-10 seconds on first use, Windows 10

### ISSUE THREAD

**Issue by Datseris** [JunoLab/atom-latex-completions#32]
I write `\div` and press tab. Until I see the dropdown menu 5 to 10 seconds pass consistently on first use.

After first use, everything is okay.

**Comment by pfitzseb** [comment]
Is this still the case? There should be absolutely no reason why this should take any perceivable time.

**Comment by Datseris** [comment]
It takes a couple of seconds yes. I definitely call this perceivable, but it is much less than when I posted this issue. It does not happen after the first time I use a latex completion.

(the progress bar runs when I do this, as if Julia is compiling something)

**Comment by pfitzseb** [comment]
Oh I see, that's just Juno's auto completions take a bit to generate on the first run.
