### ISSUE TITLE
Latex completions do not work when Julia has started

### ISSUE THREAD

**Issue by ghost** [JunoLab/atom-latex-completions#34]
When Julia has not yet started, I can do unicode characters in my script without trouble.
But when Julia, on the REPL, has started, the suggestions appear but no replacement can be made. Also, the search through the suggestions as one types the command do not work anymore.

But the package worked a week ago or so. I have tried uninstalling and reinstalling without success !

**Comment by drmartinrohde** [comment]
Confirmed, I have this issue as well. Doesn't work anymore since about 1 week. Is it related to the latest Atom update (1.33.0)?

**Comment by pfitzseb** [comment]
I'm fairly confident this happens if your Julia packages are outdated (you need Atom.jl 0.7.11). Can you confirm whether that's the case and if upgrading helps?

**Comment by ghost** [comment]
Indeed, that solved the problem, thanks !

**Comment by drmartinrohde** [comment]
I already have the julia-client 0.7.11 installed, but uninstalling and re-installing this package solved the problem. Thanks.
