### ISSUE TITLE
Latex completions do not work when Julia has started

### ISSUE THREAD

**Issue by drmartinrohde** [JunoLab/atom-latex-completions#35]
Still does not work (latest julia, latest Atom, latest julia-client). Even re-installing the julia-client and the package does not work. Interesting finding: it works in the editor as long as the REPL has not been activated. As soon as the REPL is active, latex completion in the editor does not work. It works in the REPL

**Comment by pfitzseb** [comment]
Did you try the fix proposed in #34?

**Comment by drmartinrohde** [comment]
Yes I tried by re-installing but it only works when the REPL is inactive. As soon as I start a REPL, it works in the REPL but NOT in the editor

**Comment by pfitzseb** [comment]
> I'm fairly confident this happens if your Julia packages are outdated (you need Atom.jl 0.7.11).

So you can confirm you are on Atom.jl 0.7.11? What does `pkg> status` in the REPL return?

**Comment by drmartinrohde** [comment]
Atom v0.7.10! Now I am confused. Under packages i have julia-client 0.7.11 from JunoLab. Or is this something else? Anyway, I did Pkg.update("Atom") and now it works.

**Comment by pfitzseb** [comment]
Yes, there's a distinction between Atom packages and Julia packages -- the former you can update in Atom via Settings > Updates (like you already did), wile the latter need to be updated in a Julia REPL.

Glad things are working for you now!

**Comment by drmartinrohde** [comment]
Thanks a lot for your help!
