### ISSUE TITLE
Autocomplete not working properly

### ISSUE THREAD

**Issue by clizama** [JunoLab/atom-latex-completions#37]
Hi, 

when I type tab I get the drop-down list but as I type the list does not get smaller and I still get the full list. Furthermore, if I start typing anything and then I choose one letter (ie, say I type \b and then it should show \beta) and then I type enter or tab I just get whatever I just type, but not the greek letter (in the example, I just get \b).

The only way I can use the package is by typing \ and then scroll down until I find the letter that I'm looking for (the list is pretty long, so it might take times) and then press tab or enter. 

Any ideas of what might be going on?

**Comment by pfitzseb** [comment]
Most likely something like https://github.com/JunoLab/atom-latex-completions/issues/34#issuecomment-446983687.

**Comment by clizama** [comment]
Thanks. There is something I don't understand, though. You said that package Atom.jl 0.7.11. is needed. However, I updated all the packages, and it seems that the latest version of Atom.jl is 0.6.17, am I right?

**Comment by pfitzseb** [comment]
Oh, are you still on Julia 0.6?
What version of julia-client (the Atom package) are you running?

**Comment by clizama** [comment]
Oh, that's true, I'm still in Julia 0.6.
julia-client 0.7.13 (I also uninstalled and installed again all the JunoLab packages, ie, julia-client, uber-juno, ink and obviously latex-completions)

**Comment by jebej** [comment]
also having this issue on 0.6

**Comment by uadjet** [comment]
I'm currently getting this error with 1.1.0 on OSX. Removing and reinstalling Latex-Completions from Julia and Atom has not helped. Reinstalling Atom in its entirety, including removing all configuration files has not helped either.

**Comment by pfitzseb** [comment]
Are you on version 0.7.11 of Atom.jl or higher?

**Comment by jebej** [comment]
Interestingly, when julia is not started, the completions work properly...

**Comment by jebej** [comment]
Is the reason for this issue that when julia starts, it takes over autocompletions, e.g. for functions?

If so, could we keep the latex completions working when the word starts with a backslash? That would allow writing at the same this as julia is executing something too.

**Comment by clizama** [comment]
I agree. Whenever the REPL is off (for instance, by doing command J + command K) the editor works just fine. After Julia starts, then autocomplete does not work. I think the solution you propose is a good one.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/8a3eff0436e6925c3a23867b7acfb98a230c180f. Will be in the next julia-client release. 
Do note that Juno's support for Julia 0.6 is more or less accidental by now. For the best experience you should downgrade julia-client and ink by a couple of versions.
