### ISSUE TITLE
\varphi displayed as \phi in code but not in comment

### ISSUE THREAD

**Issue by TamasPoloskei** [JunoLab/atom-latex-completions#39]
Hi,

When I would like to use the \varphi greek symbol for example in a variable's name in the autocomplete list the \phi greek symbol appears and it gets completed to it as well. See image 1.
It also happens when I would like to use \phi in a variable's name but it gets completed to \varphi.

However when I do the same thing in a comment, the autocomplete list remains to be the same but the result of the completion is the good greek character. See image 2 and 3.

![varphi_01](https://user-images.githubusercontent.com/20535545/75670945-005dbf80-5c7e-11ea-8baf-7216093551b7.png)

In the julia documentation it looks good. [unicode-input](https://docs.julialang.org/en/v1/manual/unicode-input/)

Interestingly if I use the REPL, \varphi gets completed to \phi no matter if I am writing code or a comment.

My debug info if needed:

# Atom:
Version: 1.44.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.11.0",
  "v8": "6.9.427.31-electron.0",
  "uv": "1.23.0",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "69",
  "nghttp2": "1.33.0",
  "napi": "3",
  "openssl": "1.1.0",
  "electron": "4.2.7",
  "chrome": "69.0.3497.128",
  "icu": "62.2",
  "unicode": "11.0",
  "cldr": "33.1",
  "tz": "2019a"
}
# julia-client:
Version: 0.12.2
Config:
{
  "consoleOptions": {},
  "firstBoot": false,
  "juliaOptions": {},
  "juliaPath": "C:\\Users\\PoloskeiTamasHunor\\AppData\\Local\\Julia-1.3.1\\bin\\julia.exe",
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true,
    "errorInRepl": true,
    "usePlotPane": false
  }
}

# ink:
Version: 0.12.2
Config:
undefined

# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.19.2
Config:
undefined

# language-weave:not installed

# indent-detective:
Version: 0.4.0
Config:
undefined

# latex-completions:
Version: 0.3.6
Config:
undefined

# versioninfo():
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = "C:\Users\PoloskeiTamasHunor\AppData\Local\atom\app-1.44.0\atom.exe"  -a
  JULIA_NUM_THREADS = 2

    Status `C:\Users\PoloskeiTamasHunor\.julia\environments\v1.3\Project.toml`
  [7d9fca2a] Arpack v0.4.0
  [c52e3926] Atom v0.12.7
  [6e4b80f9] BenchmarkTools v0.5.0
  [336ed68f] CSV v0.5.25
  [861a8166] Combinatorics v1.0.0
  [7a1cc6ca] FFTW v1.2.0
  [5789e2e9] FileIO v1.2.2
  [59287772] Formatting v0.4.1
  [033835bb] JLD2 v0.1.12
  [e5e0dc1b] Juno v0.8.0
  [dd61e66b] MDBM v0.1.4
  [6fe1bfb0] OffsetArrays v1.0.2
  [5fb14364] OhMyREPL v0.5.4
  [14b8a8f1] PkgTemplates v0.6.4
  [c46f51b8] ProfileView v0.6.3
  [d330b81b] PyPlot v2.8.2
  [93e0c654] Reduce v1.2.5
  [295af30f] Revise v2.5.3
  [123dc426] SymEngine v0.7.1
  [37b6cedf] Traceur v0.3.0
  [de0858da] Printf 
  [9abbd945] Profile

**Comment by pfitzseb** [comment]
This is just an "issue" with your font, which displays `\varphi` differently in italics. Looks fine with e.g. Source Code Pro:
![image](https://user-images.githubusercontent.com/6735977/75677763-75d08c80-5c8c-11ea-8019-8ef07b806f42.png)
