### ISSUE TITLE
auto-complete inside escaped bracelet in markdown

### ISSUE THREAD

**Issue by AstrickHarren** [JunoLab/atom-latex-completions#41]
I am using the markdown grammar package `language-markdown` while trying to covert latex math commands into unicode. Strangely when the cursor is put between a escaped bracelets in the (inline and/or display) math mode, the autocompletion suggestion does not pop up.
```latex
$\{\alpha\}$
```
as this `\alpha` does not activate completion suggestions. It still provokes suggestions from `snippets` with `.text.md` scope and the built-in `autocomplete-plus` though.

**Comment by pfitzseb** [comment]
I can't repro this:
![image](https://user-images.githubusercontent.com/6735977/84033733-9d28ab00-a999-11ea-9a25-92e23cedd3ee.png)

Are you sure you set the editor language correctly?

**Comment by AstrickHarren** [comment]
Problem solved. Think it was because `language-markdown` renders its math grammar with `language-latex`, and that `.latex` is in the default disable selector of `latex-completions`. The auto-fill pumped up again after enabling `.latex`.
