### ISSUE TITLE
how to select first option

### ISSUE THREAD

**Issue by mhechthz** [JunoLab/atom-latex-completions#46]
I have the problem, that the first option can only be selected if i go with cursor down and up again. If I press directly enter or space nothing happens. This is quite inconvenient.

How to get the first proposed item directly?

**Comment by pfitzseb** [comment]
Press tab. There should also be a dropdown for this in the core Atom settings.

**Comment by mhechthz** [comment]
Oh, this was too easy. <tab> is it in Jupyter and Julia REPL but I missed it here. Thank you!
