### ISSUE TITLE
\ not removed when typing very fast

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-latex-completions#6]
When typing something like `\le<tab>` very fast, I sometimes end up with `\ł`. 
This probably happens because the `e` is pressed or inserted after `tab` is pressed and the wrong characters are deleted. The expected result would be `łe`, I think. 

Not sure if that's a problem with `autocomplete-plus` instead of ours, but just thought I'd report it anyways.

More common misbehaviour: Type `\le<tab>` in the right order and you sometimes end up with `\l›` -- that's the completion for `guilsinglright`, which, in turn, is the first autocompletion in our list.

**Comment by HarrisonGrodin** [comment]
Possibly related: when typing very fast, it is possible for tab completion to remove code.

In the following GIF, I typed `\l` and finished with `e<TAB>` quickly, and then `\m` and `u<TAB>`. Both removed previous code.

![junolatexdelete](https://user-images.githubusercontent.com/25474424/27457801-e99757e6-575a-11e7-88ac-298b2ae7692c.gif)

**Comment by pfitzseb** [comment]
Should be fixed with the new version.
