### ISSUE TITLE
Superscript symbols are not typesetted

### ISSUE THREAD

**Issue by AzamatB** [JunoLab/atom-latex-completions#7]
All superscript symbols don't appear on the autocompletion list after typing `\^` and are not typesetted after manually writing e.g. `^2` among the others.

**Comment by sglyon** [comment]
I believe this has been fixed on the master branch (it works for me there)

@one-more-minute , do we need to tag this guy?

**Comment by MikeInnes** [comment]
Would be great to do a patch release – I'm releasing julia-client today anyway so I'll go ahead and get it done.

**Comment by MikeInnes** [comment]
aaaand it's done.

**Comment by AzamatB** [comment]
Wow, that was fast! Excellent! Thank you!

**Comment by MikeInnes** [comment]
No problem :)
